---
name: module3_task3

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * *' # Run at 00:00 UTC every day

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      run_id: ${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Run setup.sh
        run: ./setup.sh
        working-directory: module3_task3

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          working-directory: module3_task3

      - name: Run make build
        run: make build
        working-directory: module3_task3
      - name: Run make run
        run: make run
        working-directory: module3_task3

      - name: Run make test
        run: make test
        working-directory: module3_task3

      - name: Run make stop
        run: make stop
        working-directory: module3_task3

      - name: Package application
        run: make package
        working-directory: module3_task3

      - name: Upload package as artifact
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: awesome-website-${{ github.run_id }}
          path: awesome-website.zip

      - name: Run make clear
        run: make clean
        working-directory: module3_task3

  release:
    runs-on: ubuntu-22.04
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        if: startsWith(github.ref, 'refs/tags/')

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: awesome-website-${{ needs.build.outputs.run_id }}
          path: artifacts/
        if: startsWith(github.ref, 'refs/tags/')

      - name: Install zip
        run: sudo apt-get install zip
        if: startsWith(github.ref, 'refs/tags/')

      - name: Create zip archive
        run: |
          mkdir release-artifacts
          cp artifacts/awesome-website.zip release-artifacts/
          cp module3_task3/DEPLOY.md release-artifacts/
          zip -r awesome-website.zip release-artifacts/
        if: startsWith(github.ref, 'refs/tags/')

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: awesome-website.zip
          body_path: module3_task3/DEPLOY.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(github.ref, 'refs/tags/')
